# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - catalogue_apprentissage_nginx_data:/data:z

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app:z #Allows source folders to be watched
    build:
      args:
        - REACT_APP_ENV=dev
        - REACT_APP_ENDPOINT_NEW_FRONT=https://catalogue-recette.apprentissage.beta.gouv.fr/api
        - REACT_APP_ENDPOINT_OLD_FRONT=https://r7mayzn08d.execute-api.eu-west-3.amazonaws.com/dev
        - REACT_APP_ENDPOINT_TCO=https://tables-correspondances-recette.apprentissage.beta.gouv.fr/api

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src:z # Allows source folders to be watched
      - ./server/config:/app/config:z
      - catalogue_apprentissage_server_data:/data:z
    env_file: ./server/.env
    environment:
      - CATALOGUE_APPRENTISSAGE_ENV=dev
      - CATALOGUE_APPRENTISSAGE_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - catalogue_apprentissage_mongodb_data:/data:z

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - catalogue_apprentissage_data_elasticsearch:/usr/share/elasticsearch/data:z
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z

  kibana:
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z

volumes:
  catalogue_apprentissage_data_elasticsearch:
    driver: local
    name: catalogue_apprentissage_data_elasticsearch
  catalogue_apprentissage_mongodb_data:
    driver: local
    name: catalogue_apprentissage_mongodb_data
  catalogue_apprentissage_nginx_data:
    driver: local
    name: catalogue_apprentissage_nginx_data
  catalogue_apprentissage_server_data:
    driver: local
    name: catalogue_apprentissage_server_data
