version: "2.4"
services:
  reverse_proxy:
    image: catalogue_apprentissage_reverse_proxy
    container_name: catalogue_apprentissage_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - catalogue_apprentissage_network
    depends_on:
      - server
      - ui

  ui:
    image: catalogue_apprentissage_ui
    container_name: catalogue_apprentissage_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - catalogue_apprentissage_network
    depends_on:
      - server

  server:
    image: catalogue_apprentissage_server
    container_name: catalogue_apprentissage_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - catalogue_apprentissage_network
    depends_on:
      - mongodb
    environment:
      - CATALOGUE_APPRENTISSAGE_MONGODB_URI=mongodb://mongodb:27017/catalogue-apprentissage?retryWrites=true&w=majority
      - NODE_ICU_DATA=node_modules/full-icu

  mongodb:
    image: mongo:4.2.6-bionic
    container_name: catalogue_apprentissage_mongodb
    mem_limit: 8g
    restart: unless-stopped
    networks:
      - catalogue_apprentissage_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.1
    container_name: catalogue_apprentissage_elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - discovery.type=single-node
    mem_limit: 1g
    networks:
      - catalogue_apprentissage_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.1
    container_name: catalogue_apprentissage_kibana
    depends_on:
      - elasticsearch
    networks:
      - catalogue_apprentissage_network
    environment:
      - SERVER_BASEPATH=/kibana

networks:
  catalogue_apprentissage_network:
    name: catalogue_apprentissage_network
