# Worflow pour IC
name: Yarn CI Server

on: [push]

jobs:
  # Single job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2

      # setup npmrc
      - run: echo -e "//npm.pkg.github.com/:_authToken=$NPM_TOKEN\n@mission-apprentissage:registry=https://npm.pkg.github.com" > server/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Install dependencies
      - name: Run Yarn Install
        run: |
          cd server
          yarn install

      # Lint
      - name: Run Lint
        run: |
          cd server
          yarn lint

      # # Start dockers containers
      # - name: Start Docker
      #   run: |
      #     cd server
      #     yarn docker:start

      # # Run mocha tests
      # - name: Run Tests
      #   run: |
      #     cd server
      #     yarn test
      #     yarn jobs:test
